<?php
/**
 * DesignElementType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Design Atoms API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\DesignAtoms\Model;
use \Aurigma\DesignAtoms\ObjectSerializer;

/**
 * DesignElementType Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DesignElementType
{
    /**
     * Possible values of this enum
     */
    public const PRODUCT = 'Product';

    public const DESIGN = 'Design';

    public const SURFACE = 'Surface';

    public const CONTAINER = 'Container';

    public const PRINT_AREA = 'PrintArea';

    public const ITEM = 'Item';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PRODUCT,
            self::DESIGN,
            self::SURFACE,
            self::CONTAINER,
            self::PRINT_AREA,
            self::ITEM
        ];
    }
}


