<?php
/**
 * ImagePreviewFitMode
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Design Atoms API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\DesignAtoms\Model;
use \Aurigma\DesignAtoms\ObjectSerializer;

/**
 * ImagePreviewFitMode Class Doc Comment
 *
 * @category Class
 * @description Image preview fit mode.
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ImagePreviewFitMode
{
    /**
     * Possible values of this enum
     */
    public const FIT = 'Fit';

    public const SHRINK = 'Shrink';

    public const RESIZE = 'Resize';

    public const FILL = 'Fill';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FIT,
            self::SHRINK,
            self::RESIZE,
            self::FILL
        ];
    }
}


