<?php
/**
 * ImagePreviewFormat
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DesignAtoms API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\DesignAtoms\Model;
use \Aurigma\DesignAtoms\ObjectSerializer;

/**
 * ImagePreviewFormat Class Doc Comment
 *
 * @category Class
 * @description Image preview file format.
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ImagePreviewFormat
{
    /**
     * Possible values of this enum
     */
    public const JPEG = 'Jpeg';

    public const PNG = 'Png';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::JPEG,
            self::PNG
        ];
    }
}


