<?php
/**
 * ProductPatchType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DesignAtoms API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\DesignAtoms\Model;
use \Aurigma\DesignAtoms\ObjectSerializer;

/**
 * ProductPatchType Class Doc Comment
 *
 * @category Class
 * @description Available patch type.
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductPatchType
{
    /**
     * Possible values of this enum
     */
    public const UNDEFINED = 'Undefined';

    public const REPLACE_IMAGE_ITEM_FILE = 'ReplaceImageItemFile';

    public const REPLACE_PLACEHOLDER_ITEM_CONTENT = 'ReplacePlaceholderItemContent';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNDEFINED,
            self::REPLACE_IMAGE_ITEM_FILE,
            self::REPLACE_PLACEHOLDER_ITEM_CONTENT
        ];
    }
}


