<?php
/**
 * RenderImagePreviewToResourceModel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Design Atoms API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\DesignAtoms\Model;

use \ArrayAccess;
use \Aurigma\DesignAtoms\ObjectSerializer;

/**
 * RenderImagePreviewToResourceModel Class Doc Comment
 *
 * @category Class
 * @description Image preview rendering parameters. Result will be saved as resource with parameters set as Aurigma.DesignAtomsApi.WebApi.Models.Image.RenderImagePreviewToResourceModel.PreviewResourceParams.
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RenderImagePreviewToResourceModel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RenderImagePreviewToResourceModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'preview_resource_params' => '\Aurigma\DesignAtoms\Model\RenderDesignPreviewToResourceModelPreviewResourceParams',
        'overwrite_existing_resource' => 'bool',
        'image_url' => 'string',
        'image_id' => 'string',
        'owner_id' => 'string',
        'mockup_owner_id' => 'string',
        'mockup_id' => 'string',
        'rendering_config' => '\Aurigma\DesignAtoms\Model\RenderImagePreviewFromUrlModelRenderingConfig'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'preview_resource_params' => null,
        'overwrite_existing_resource' => null,
        'image_url' => null,
        'image_id' => null,
        'owner_id' => null,
        'mockup_owner_id' => null,
        'mockup_id' => null,
        'rendering_config' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'preview_resource_params' => true,
        'overwrite_existing_resource' => false,
        'image_url' => true,
        'image_id' => true,
        'owner_id' => true,
        'mockup_owner_id' => true,
        'mockup_id' => true,
        'rendering_config' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'preview_resource_params' => 'previewResourceParams',
        'overwrite_existing_resource' => 'overwriteExistingResource',
        'image_url' => 'imageUrl',
        'image_id' => 'imageId',
        'owner_id' => 'ownerId',
        'mockup_owner_id' => 'mockupOwnerId',
        'mockup_id' => 'mockupId',
        'rendering_config' => 'renderingConfig'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'preview_resource_params' => 'setPreviewResourceParams',
        'overwrite_existing_resource' => 'setOverwriteExistingResource',
        'image_url' => 'setImageUrl',
        'image_id' => 'setImageId',
        'owner_id' => 'setOwnerId',
        'mockup_owner_id' => 'setMockupOwnerId',
        'mockup_id' => 'setMockupId',
        'rendering_config' => 'setRenderingConfig'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'preview_resource_params' => 'getPreviewResourceParams',
        'overwrite_existing_resource' => 'getOverwriteExistingResource',
        'image_url' => 'getImageUrl',
        'image_id' => 'getImageId',
        'owner_id' => 'getOwnerId',
        'mockup_owner_id' => 'getMockupOwnerId',
        'mockup_id' => 'getMockupId',
        'rendering_config' => 'getRenderingConfig'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('preview_resource_params', $data ?? [], null);
        $this->setIfExists('overwrite_existing_resource', $data ?? [], null);
        $this->setIfExists('image_url', $data ?? [], null);
        $this->setIfExists('image_id', $data ?? [], null);
        $this->setIfExists('owner_id', $data ?? [], null);
        $this->setIfExists('mockup_owner_id', $data ?? [], null);
        $this->setIfExists('mockup_id', $data ?? [], null);
        $this->setIfExists('rendering_config', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets preview_resource_params
     *
     * @return \Aurigma\DesignAtoms\Model\RenderDesignPreviewToResourceModelPreviewResourceParams|null
     */
    public function getPreviewResourceParams()
    {
        return $this->container['preview_resource_params'];
    }

    /**
     * Sets preview_resource_params
     *
     * @param \Aurigma\DesignAtoms\Model\RenderDesignPreviewToResourceModelPreviewResourceParams|null $preview_resource_params preview_resource_params
     *
     * @return self
     */
    public function setPreviewResourceParams($preview_resource_params)
    {
        if (is_null($preview_resource_params)) {
            array_push($this->openAPINullablesSetToNull, 'preview_resource_params');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('preview_resource_params', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['preview_resource_params'] = $preview_resource_params;

        return $this;
    }

    /**
     * Gets overwrite_existing_resource
     *
     * @return bool|null
     */
    public function getOverwriteExistingResource()
    {
        return $this->container['overwrite_existing_resource'];
    }

    /**
     * Sets overwrite_existing_resource
     *
     * @param bool|null $overwrite_existing_resource Flag that indicates if an existing resource should be overwritten.
     *
     * @return self
     */
    public function setOverwriteExistingResource($overwrite_existing_resource)
    {
        if (is_null($overwrite_existing_resource)) {
            throw new \InvalidArgumentException('non-nullable overwrite_existing_resource cannot be null');
        }
        $this->container['overwrite_existing_resource'] = $overwrite_existing_resource;

        return $this;
    }

    /**
     * Gets image_url
     *
     * @return string|null
     * @deprecated
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param string|null $image_url External image URL.
     *
     * @return self
     * @deprecated
     */
    public function setImageUrl($image_url)
    {
        if (is_null($image_url)) {
            array_push($this->openAPINullablesSetToNull, 'image_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('image_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets image_id
     *
     * @return string|null
     */
    public function getImageId()
    {
        return $this->container['image_id'];
    }

    /**
     * Sets image_id
     *
     * @param string|null $image_id Storage image identifier.
     *
     * @return self
     */
    public function setImageId($image_id)
    {
        if (is_null($image_id)) {
            array_push($this->openAPINullablesSetToNull, 'image_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('image_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['image_id'] = $image_id;

        return $this;
    }

    /**
     * Gets owner_id
     *
     * @return string|null
     */
    public function getOwnerId()
    {
        return $this->container['owner_id'];
    }

    /**
     * Sets owner_id
     *
     * @param string|null $owner_id Storage image owner identifier.
     *
     * @return self
     */
    public function setOwnerId($owner_id)
    {
        if (is_null($owner_id)) {
            array_push($this->openAPINullablesSetToNull, 'owner_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('owner_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['owner_id'] = $owner_id;

        return $this;
    }

    /**
     * Gets mockup_owner_id
     *
     * @return string|null
     */
    public function getMockupOwnerId()
    {
        return $this->container['mockup_owner_id'];
    }

    /**
     * Sets mockup_owner_id
     *
     * @param string|null $mockup_owner_id Mockup owner identifier.
     *
     * @return self
     */
    public function setMockupOwnerId($mockup_owner_id)
    {
        if (is_null($mockup_owner_id)) {
            array_push($this->openAPINullablesSetToNull, 'mockup_owner_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mockup_owner_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mockup_owner_id'] = $mockup_owner_id;

        return $this;
    }

    /**
     * Gets mockup_id
     *
     * @return string|null
     */
    public function getMockupId()
    {
        return $this->container['mockup_id'];
    }

    /**
     * Sets mockup_id
     *
     * @param string|null $mockup_id Mockup identifier.
     *
     * @return self
     */
    public function setMockupId($mockup_id)
    {
        if (is_null($mockup_id)) {
            array_push($this->openAPINullablesSetToNull, 'mockup_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mockup_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mockup_id'] = $mockup_id;

        return $this;
    }

    /**
     * Gets rendering_config
     *
     * @return \Aurigma\DesignAtoms\Model\RenderImagePreviewFromUrlModelRenderingConfig|null
     */
    public function getRenderingConfig()
    {
        return $this->container['rendering_config'];
    }

    /**
     * Sets rendering_config
     *
     * @param \Aurigma\DesignAtoms\Model\RenderImagePreviewFromUrlModelRenderingConfig|null $rendering_config rendering_config
     *
     * @return self
     */
    public function setRenderingConfig($rendering_config)
    {
        if (is_null($rendering_config)) {
            array_push($this->openAPINullablesSetToNull, 'rendering_config');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('rendering_config', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['rendering_config'] = $rendering_config;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


