<?php
/**
 * CreateItemFromStorageModelTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Design Atoms API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aurigma\DesignAtoms\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateItemFromStorageModelTest Class Doc Comment
 *
 * @category    Class
 * @description Create item from storage source operation parameters.
 * @package     Aurigma\DesignAtoms
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateItemFromStorageModelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateItemFromStorageModel"
     */
    public function testCreateItemFromStorageModel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "source_owner_id"
     */
    public function testPropertySourceOwnerId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "source_id"
     */
    public function testPropertySourceId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "palette_uid"
     */
    public function testPropertyPaletteUid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "page_index"
     */
    public function testPropertyPageIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "preserve_original_file"
     */
    public function testPropertyPreserveOriginalFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
