<?php
/**
 * DesignParametersMeasureUnitTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Design Atoms API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aurigma\DesignAtoms\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DesignParametersMeasureUnitTest Class Doc Comment
 *
 * @category    Class
 * @description Design measure unit description.
 * @package     Aurigma\DesignAtoms
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DesignParametersMeasureUnitTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DesignParametersMeasureUnit"
     */
    public function testDesignParametersMeasureUnit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "short_name"
     */
    public function testPropertyShortName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ratio"
     */
    public function testPropertyRatio()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
