<?php
/**
 * RenderDesignProofModelTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Design Atoms API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aurigma\DesignAtoms\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RenderDesignProofModelTest Class Doc Comment
 *
 * @category    Class
 * @description RenderDesignProofModel
 * @package     Aurigma\DesignAtoms
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RenderDesignProofModelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RenderDesignProofModel"
     */
    public function testRenderDesignProofModel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "design_id"
     */
    public function testPropertyDesignId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "owner_id"
     */
    public function testPropertyOwnerId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rendering_config"
     */
    public function testPropertyRenderingConfig()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "variable_data"
     */
    public function testPropertyVariableData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
