<?php
/**
 * DesignAtomsPrintProductItemsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Design Atoms API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\DesignAtoms\Test\Api;

use \Aurigma\DesignAtoms\Configuration;
use \Aurigma\DesignAtoms\ApiException;
use \Aurigma\DesignAtoms\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DesignAtomsPrintProductItemsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DesignAtomsPrintProductItemsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for designAtomsPrintProductItemsApplyItemEffects
     *
     * Apply effects to print-product item image..
     *
     */
    public function testDesignAtomsPrintProductItemsApplyItemEffects()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsPrintProductItemsBatchCreateItemsFromFile
     *
     * Creates multiple print-product items from input image files..
     *
     */
    public function testDesignAtomsPrintProductItemsBatchCreateItemsFromFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsPrintProductItemsBatchCreateItemsFromStorage
     *
     * Creates multiple print-product items from the specified image files in storage..
     *
     */
    public function testDesignAtomsPrintProductItemsBatchCreateItemsFromStorage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsPrintProductItemsBatchCreateItemsFromUrl
     *
     * Creates multiple print-product items from remote web images provided by URLs list..
     *
     */
    public function testDesignAtomsPrintProductItemsBatchCreateItemsFromUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsPrintProductItemsCreateItemFromFile
     *
     * Creates print-product item from input image file..
     *
     */
    public function testDesignAtomsPrintProductItemsCreateItemFromFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsPrintProductItemsCreateItemFromStorage
     *
     * Creates print-product item from image file taken from storage..
     *
     */
    public function testDesignAtomsPrintProductItemsCreateItemFromStorage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsPrintProductItemsCreateItemFromUrl
     *
     * Creates print-product item from remote web image provided by URL..
     *
     */
    public function testDesignAtomsPrintProductItemsCreateItemFromUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsPrintProductItemsExtractItemImage
     *
     * Extracts print-product item image..
     *
     */
    public function testDesignAtomsPrintProductItemsExtractItemImage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsPrintProductItemsExtractItemImageToResource
     *
     * Extracts print-product item image..
     *
     */
    public function testDesignAtomsPrintProductItemsExtractItemImageToResource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsPrintProductItemsFlattenItems
     *
     * Flattens print-product items..
     *
     */
    public function testDesignAtomsPrintProductItemsFlattenItems()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
