<?php
/**
 * DesignAtomsServiceApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Design Atoms API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\DesignAtoms\Test\Api;

use \Aurigma\DesignAtoms\Configuration;
use \Aurigma\DesignAtoms\ApiException;
use \Aurigma\DesignAtoms\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DesignAtomsServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DesignAtomsServiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for designAtomsServiceConvertColors
     *
     * Converts colors for print-product item manipulations..
     *
     */
    public function testDesignAtomsServiceConvertColors()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceCreateDesign
     *
     * Creates new design file with specified parameters and saves it in storage..
     *
     */
    public function testDesignAtomsServiceCreateDesign()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceCreateItem
     *
     * Creates print-product item..
     *
     */
    public function testDesignAtomsServiceCreateItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceCreatePrivateDesignFromDesign
     *
     * Creates a private design from a public design..
     *
     */
    public function testDesignAtomsServiceCreatePrivateDesignFromDesign()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceCreatePrivateDesignFromResource
     *
     * Creates a private design from a public resource..
     *
     */
    public function testDesignAtomsServiceCreatePrivateDesignFromResource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceDeleteVdpData
     *
     * Deletes variable data printing information from design file and updates design file in storage..
     *
     */
    public function testDesignAtomsServiceDeleteVdpData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceExtractBackground
     *
     * Returns image content of the background..
     *
     */
    public function testDesignAtomsServiceExtractBackground()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceExtractItemImage
     *
     * Extracts print-product item image..
     *
     */
    public function testDesignAtomsServiceExtractItemImage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceFlattenItems
     *
     * Flattens print-product items..
     *
     */
    public function testDesignAtomsServiceFlattenItems()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceGetDesignParameters
     *
     * Returns design parameters stored in product model..
     *
     */
    public function testDesignAtomsServiceGetDesignParameters()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceGetVariables
     *
     * Returns variable items information for design file taken from storage..
     *
     */
    public function testDesignAtomsServiceGetVariables()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceLoadDataSchema
     *
     * Loads a data schema from design file taken from storage..
     *
     */
    public function testDesignAtomsServiceLoadDataSchema()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceLoadProduct
     *
     * Loads print-product from design file taken from storage..
     *
     */
    public function testDesignAtomsServiceLoadProduct()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceLoadProductFromResource
     *
     * Loads print-product from resource file taken from storage..
     *
     */
    public function testDesignAtomsServiceLoadProductFromResource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceLoadToggleSet
     *
     * Loads a toggle set from design file taken from storage..
     *
     */
    public function testDesignAtomsServiceLoadToggleSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceLoadVdpData
     *
     * Loads variable data printing information from design file taken from storage..
     *
     */
    public function testDesignAtomsServiceLoadVdpData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServicePatchProduct
     *
     * Patches print-product in design file..
     *
     */
    public function testDesignAtomsServicePatchProduct()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceRenderDesignPreview
     *
     * Renders a design preview with the specified parameters..
     *
     */
    public function testDesignAtomsServiceRenderDesignPreview()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceRenderDesignPreviewToResource
     *
     * Renders a design preview with the specified parameters and saves rendering result as resource..
     *
     */
    public function testDesignAtomsServiceRenderDesignPreviewToResource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceRenderDesignProof
     *
     * Renders a design proof with the specified parameters..
     *
     */
    public function testDesignAtomsServiceRenderDesignProof()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceRenderDesignProofToResource
     *
     * Renders a design proof with the specified parameters and saves rendering result as resource..
     *
     */
    public function testDesignAtomsServiceRenderDesignProofToResource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceRenderProduct
     *
     * Renders a product proof image with specified parameters..
     *
     */
    public function testDesignAtomsServiceRenderProduct()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceSaveProduct
     *
     * Saves print-product to design file and updates design file in storage..
     *
     */
    public function testDesignAtomsServiceSaveProduct()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceSaveVdpData
     *
     * Saves variable data printing information to design file and updates design in storage..
     *
     */
    public function testDesignAtomsServiceSaveVdpData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceSetEditorMockups
     *
     * Sets specified editor-mockups for selected design surfaces..
     *
     */
    public function testDesignAtomsServiceSetEditorMockups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsServiceSetVariables
     *
     * Saves variable items values for design file taken from storage..
     *
     */
    public function testDesignAtomsServiceSetVariables()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
