<?php
/**
 * DesignAtomsViewerApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Design Atoms API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\DesignAtoms\Test\Api;

use \Aurigma\DesignAtoms\Configuration;
use \Aurigma\DesignAtoms\ApiException;
use \Aurigma\DesignAtoms\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DesignAtomsViewerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\DesignAtoms
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DesignAtomsViewerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for designAtomsViewerCssFonts
     *
     * .
     *
     */
    public function testDesignAtomsViewerCssFonts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerFonts
     *
     * .
     *
     */
    public function testDesignAtomsViewerFonts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerGetColorPreview
     *
     * .
     *
     */
    public function testDesignAtomsViewerGetColorPreview()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerGetColorPreviews
     *
     * .
     *
     */
    public function testDesignAtomsViewerGetColorPreviews()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerGetCssFont
     *
     * .
     *
     */
    public function testDesignAtomsViewerGetCssFont()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerGetFallbackFonts
     *
     * .
     *
     */
    public function testDesignAtomsViewerGetFallbackFonts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerGetImageSize
     *
     * .
     *
     */
    public function testDesignAtomsViewerGetImageSize()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerGetLicense
     *
     * .
     *
     */
    public function testDesignAtomsViewerGetLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerGetShapeBounds
     *
     * .
     *
     */
    public function testDesignAtomsViewerGetShapeBounds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerGetWatermarkItems
     *
     * .
     *
     */
    public function testDesignAtomsViewerGetWatermarkItems()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerImg
     *
     * Retrieves an image with resized dimensions and additional visual effects based on the provided parameters..
     *
     */
    public function testDesignAtomsViewerImg()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerPth
     *
     * .
     *
     */
    public function testDesignAtomsViewerPth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerResource
     *
     * .
     *
     */
    public function testDesignAtomsViewerResource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerSvg
     *
     * .
     *
     */
    public function testDesignAtomsViewerSvg()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerTxt
     *
     * .
     *
     */
    public function testDesignAtomsViewerTxt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerUpdateArchedTextItemHandler
     *
     * .
     *
     */
    public function testDesignAtomsViewerUpdateArchedTextItemHandler()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerUpdateAutoScaledTextItemHandler
     *
     * .
     *
     */
    public function testDesignAtomsViewerUpdateAutoScaledTextItemHandler()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerUpdateBarcodeItemHandler
     *
     * .
     *
     */
    public function testDesignAtomsViewerUpdateBarcodeItemHandler()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerUpdateBoundedTextItemHandler
     *
     * .
     *
     */
    public function testDesignAtomsViewerUpdateBoundedTextItemHandler()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerUpdateByColorData
     *
     * .
     *
     */
    public function testDesignAtomsViewerUpdateByColorData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerUpdateByMultiCallRequest
     *
     * .
     *
     */
    public function testDesignAtomsViewerUpdateByMultiCallRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerUpdateCurvedTextItemHandler
     *
     * .
     *
     */
    public function testDesignAtomsViewerUpdateCurvedTextItemHandler()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerUpdateImageItemHandler
     *
     * .
     *
     */
    public function testDesignAtomsViewerUpdateImageItemHandler()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerUpdatePathBoundedTextItemHandler
     *
     * .
     *
     */
    public function testDesignAtomsViewerUpdatePathBoundedTextItemHandler()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerUpdatePlainTextItemHandler
     *
     * .
     *
     */
    public function testDesignAtomsViewerUpdatePlainTextItemHandler()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designAtomsViewerUpdateShapeItemHandler
     *
     * .
     *
     */
    public function testDesignAtomsViewerUpdateShapeItemHandler()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
